---
# tasks file for vmware-vm

  - name: get guest facts
    vmware_guest_facts:


  - name: create a VM in esxi
    vmware_guest:
      hostname: "{{ vmware_vm.vm.hostname }}"
      username: "{{ vmware_vm.vm.username }}"
      password: "{{ vmware_vm.vm.password }}"
      validate_certs: "{{ vmware_vm.vm.validate_certs }}"
      folder: "{{ vmware_vm.vm.folder }}"
      name: "{{ vmware_vm.vm.name }}"
      state: "{{ vmware_vm.vm.state }}"
      template: "{{ vmware_vm.vm.template }}"
      disk: 
      hardware:
      networks:
      delegate_to:


